name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Запуск тестов
      - name: Run tests
        run: |
          pytest