name: CI Pipeline

on: # Триггеры
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Загружаем код репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Укажите нужную версию

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4. Запускаем сборку
      - name: Build project
        run: npm run build

      # 5. Запускаем тесты
      - name: Run tests
        run: npm test

      # 6. (Опционально) Загружаем артефакты (результаты сборки)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: build-output
          path: dist/  # Путь к собранным файлам